### ISSUE TITLE
No exe file

### ISSUE THREAD

**Issue by owerrride** [Geuthur/EVE-Alert#11]
Hi, I encountered this problem:
after running the installation script, a dist folder appears, but there is no executable file in it, just a folder: evealert and inside 2 folders: images and sound. There is nothing else...
OS Win 11

**Comment by Geuthur** [comment]
Hello did you have python installed this can happen if Python is not installed on your OS

https://www.python.org/downloads/

Important is that you check in the CMD feature.

**Comment by owerrride** [comment]
> Важно, чтобы вы проверили функцию CMD.

Yes, python is installed. How can I check the cmd function?

**Comment by Geuthur** [comment]
it is in the installation as a optional option.

the same issue has another user and it works for him after he activate that
