### ISSUE TITLE
Help please.

### ISSUE THREAD

**Issue by 9564519** [Geuthur/EVE-Alert#12]
It seems I can't compile the program. I can show screenshots, I guess I'm doing something wrong.
But maybe there is another solution?
Please, can you upload the release files? So that I don't have to do any preliminary actions with PYTHON? Console, etc.?

**Comment by Geuthur** [comment]
Hey @9564519,

Please look at https://github.com/Geuthur/EVE-Alert-Opensource/blob/main/INSTALL.md
Maybe you have not activate `Add python.exe to PATH` this is important to work.

Also i have updated the installer_window.bat maybe this will fix your issue.

Cheers

**Comment by 9564519** [comment]
i.e. you don't want it simple )))
And you want to understand the situation.
Okay, Here it is -
I downloaded a new version of the distribution, but the problem remains the same - see the screenshot https://imgur.com/a/IsALLnp .
I can post it in text if needed?
It seems I don't have a problem with Pit, (Python itself just has a lot of problems - I don't like it, call me.)

**Comment by Geuthur** [comment]
I will look at it i am not sure if i can fix that cause it give me not enough information maybe Numpy is also a problem i see i will look if I found a Solution

I tryt it with my Computer on Windows 11 and it works fine.

**Comment by 9564519** [comment]
I immediately wrote that solving a private problem is a bad way to solve it.
The application should be standardized. The application should work in any environment.

Maybe it is possible to come up with something? Something reliable?

**Comment by Geuthur** [comment]
maybe maybe not.
