### ISSUE TITLE
Also, Alarm doesn't ring when red star is in local.

### ISSUE THREAD

**Issue by gpangmin** [Geuthur/EVE-Alert#2]
![202402_001316](https://github.com/Geuthur/EVE-Alert/assets/130155101/9fe46726-6edb-4dd9-a2e2-9ef6f1508791)

Alert can't detect that Red star icon.

I tried to change that icon in folder by screenshot,

it worked but now blue star(alliance) and purple star(fleet) is ringing too.

**Comment by Geuthur** [comment]
I updated some Code maybe now it works for you.

Please also check, If your detection accuracy is fine or high enough to filter similar icons - If you change the scale you need to press save to see the new result.

Also a Issue can be the ingame Scale try it with 100%

i tested it with my new laptop and it works only if i have 100% scale
![Screenshot 2024-02-05 143439](https://github.com/Geuthur/EVE-Alert/assets/761682/afb8d795-0965-4b18-8504-001de09110b5)

![Screenshot 2024-02-05 143507](https://github.com/Geuthur/EVE-Alert/assets/761682/a527f4ad-34b9-4164-b5d6-c55f3fd52cb0)

**Comment by gpangmin** [comment]
thanks for updating,
but new bug found : now alarm rings when green star(same corperation member) comes.
accuracy is 100%, and UI scale is 100% too. idk what did i do wrong...

![202402_001340](https://github.com/Geuthur/EVE-Alert/assets/130155101/3586351b-4099-44a1-8678-f9cee86572eb)

**Comment by Geuthur** [comment]
I think the simplest fix is to set the icon blue, I see that this was not detected.

Some of my guys tested the Alert and they said it works fine for all icons also with the color.

Maybe there is a special case for you, I can't reproduce it.
I check'd also different settings and it works fine.

For your case it is only possible to change the color of the icon or you use the color mode then it will alert on red color in the area.
