### ISSUE TITLE
Unable to detect neutral enemy

### ISSUE THREAD

**Issue by anxiousottergames** [Geuthur/EVE-Alert#3]
Hi, I got the program working to detect the red enemy but unable to detect neutral players. 
Solution:Used the screenshot (F3) button to create a new neutral player png -> and change it to image_5.png and restart the program

It also pings faction (blue) players.
Solution: increase the threshold

When I go to settings -> Check the detection mode, this error appeared
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "customtkinter\windows\widgets\ctk_checkbox.py", line 423, in toggle
  File "evealert\menus\configuration.py", line 240, in update_mode
AttributeError: 'AlertAgent' object has no attribute 'get_vision'

**Comment by anxiousottergames** [comment]
Nevermind, seems faction player is due to lowered threshold

**Comment by Geuthur** [comment]
This is fixed now.

Thanks i tested it.

Maybe it is a Resolution Problem but in Colormode normally it works fine.
