### ISSUE TITLE
Numpy issue

### ISSUE THREAD

**Issue by Inspired2150** [Geuthur/EVE-Alert#5]
![image](https://github.com/Geuthur/EVE-Alert-Opensource/assets/12717767/8a8a5e0c-d246-46c9-8aab-a00861047821)
Heya! I'm not a developer or a coder in any way, but I am getting this issue I'm not sure how to solve.
I tried installing the latest version (0.4.1.1) on 3 different machines with the same error.

Version 0.4.1, however, works great without any issues. 

I seem to have numpy installed on my machine, but no idea if it's the correct version.
![image](https://github.com/Geuthur/EVE-Alert-Opensource/assets/12717767/924606e7-339c-4ea7-a501-f223c08feb5e)

Edit: The version of Python I am using is 3.12.4

**Comment by Geuthur** [comment]
Should work now.
