### ISSUE TITLE
ico error

### ISSUE THREAD

**Issue by xrizonx** [Geuthur/EVE-Alert#9]
Hi,

Trying to install this on Garuda Linux but facing issuese with .ico and some other stuff below any fix?

░░░░░░░░░░░░░░░░░ Geuthur - EVE Alert v0.4.1.1 ░░░░░░░░░░░░░░░░░

ALSA lib pcm_dsnoop.c:567:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2722:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:404:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_a52.c:1036:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:481:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:481:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
File "main.py", line 53, in <module>
File "evealert/menus/alert.py", line 116, in __init__
File "evealert/menus/configuration.py", line 14, in __init__
File "customtkinter/windows/ctk_tk.py", line 232, in iconbitmap
File "tkinter/__init__.py", line 2154, in wm_iconbitmap
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"
[38643] Failed to execute script 'main' due to unhandled exception!

**Comment by Geuthur** [comment]
Try this

https://github.com/Geuthur/EVE-Alert-Opensource/archive/refs/heads/9-ico-error.zip

Let me know if the bug is fixed.
